# Generated by Django 3.0.5 on 2020-05-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('ptype', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('cost', models.FloatField()),
                ('revenue', models.FloatField()),
                ('profit', models.FloatField()),
            ],
        ),
    ]
