# Generated by Django 3.0.6 on 2020-05-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='is_like',
            field=models.BooleanField(),
        ),
    ]
